language: csharp
dotnet: 2.1.401
git:
  depth: false
before_script:
  - nuget install docfx.console -ExcludeVersion
  - export DOCFX_TOOL="mono docfx.console/tools/docfx.exe"
script:
  - chmod +x ./build.sh
  - ./build.sh All -ApiKey $NUGET_API_KEY -GithubUsername $GITHUB_USERNAME -GithubToken $GITHUB_TOKEN -DocFxTool "$DOCFX_TOOL"